# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "@ijarquinmedina's blog"
email: isaacjarquin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Series of posts about software engineering and best practices. We will talk about OOP, functional programming and Agile best practices.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://isaacjarquin.github.io" # the base hostname & protocol for your site
twitter_username: "@ijarquinmedina"
github_username: isaacjarquin
gems:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
